#ifndef COMMONMETHOD1_GLOBAL_H
#define COMMONMETHOD1_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMONMETHOD1_LIBRARY)
#  define COMMONMETHOD1SHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMONMETHOD1SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMONMETHOD1_GLOBAL_H
