#ifndef NETWORKBASE_GLOBAL_H
#define NETWORKBASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NETWORKBASE_LIBRARY)
#  define NETWORKBASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define NETWORKBASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NETWORKBASE_GLOBAL_H
